version: '3'
services:
  bot:
    build:
      context: .
    env_file:
      - .env
    command: "python wp_bot/bot.py"
    volumes:
      - ./context:/opt/wp_bot/context
      - ./media:/opt/wp_bot/media
      - ./log:/opt/wp_bot/log
    
    